trigger:
  - master
variables:
  buildConfiguration: Release
stages:
  - stage: Build
    jobs:
      - job: PipelineLearningsBuild
        pool: null
        vmImage: vs2017-win2016
        steps:
          - task: DotNetCoreCLI@2
            inputs: null
            command: build
            projects: pipelines-dotnet-core.csproj
            arguments: '--configuration $(BuildConfiguration)'
            feedsToUse: select
            versioningScheme: off
          - task: DotNetCoreCLI@2
            inputs: null
            command: publish
            publishWebProjects: false
            projects: pipelines-dotnet-core.csproj
            arguments: >-
              --configuration $(BuildConfiguration) --output
              $(build.artifactstagingdirectory)
            feedsToUse: select
            versioningScheme: off
          - task: PublishBuildArtifacts@1
            inputs: null
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: drop
            publishLocation: Container
  - stage: DevRelease
    jobs:
      - job: DevRelease
        pool: null
        vmImage: vs2017-win2016
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs: null
            ConnectionType: AzureRM
            azureSubscription: Visual Studio Enterprise (5ae35b9e-9571-4a30-8426-62c1ba3394c4)
            appType: webApp
            WebAppName: PartsUnlimitedLD
            packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip
